services:
  data_load:
    build: ./src/data_load
    volumes:
      - ./data:/app/data
      - shared_db:/app/db

  quality_analysis:
    build: ./src/quality
    volumes:
      - shared_db:/app/db
      - ./reports:/app/reports
    depends_on:
      data_load:
        condition: service_completed_successfully

  research:
    build: ./src/research
    volumes:
      - shared_db:/app/db
      - ./reports:/app/reports
    depends_on:
      data_load:
        condition: service_completed_successfully

  visualization:
    build: ./src/visualization
    volumes:
      - shared_db:/app/db
      - ./reports:/app/reports
    depends_on:
      data_load:
        condition: service_completed_successfully

  web:
    build: ./src/web
    ports:
      - "8501:8501"
    volumes:
      - ./reports:/app/reports
    depends_on:
      visualization:
        condition: service_completed_successfully
      quality_analysis:
        condition: service_completed_successfully
      research:
        condition: service_completed_successfully

volumes:
  shared_db: