apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: my-app-prod
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: maksymlirko/lab6_web:v1
        ports:
        - containerPort: 8501
