name: CI modules

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      module:
        description: 'Module to test'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - data_load
        - quality
        - research
        - visualize

jobs:
  run_modules:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module: ["data_load", "quality", "research", "visualize"]

    steps:
      - name: Checkout code
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        uses: actions/checkout@v4

      - name: Check changed files
        if: github.event_name != 'workflow_dispatch'
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            module_changed:
              - 'src/${{ matrix.module }}.py'
              - 'tests/test_${{ matrix.module }}.py'
              - 'requirements.txt'

      - name: Decide if module should run
        id: check
        run: |
                if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
                  if [ "${{ inputs.module }}" == "all" ] || [ "${{ inputs.module }}" == "${{ matrix.module }}" ]; then
                    echo "run=true" >> $GITHUB_OUTPUT
                  else
                    echo "run=false" >> $GITHUB_OUTPUT
                  fi
                else
                  if [ "${{ steps.filter.outputs.module_changed }}" == "true" ]; then
                    echo "run=true" >> $GITHUB_OUTPUT
                  else
                    echo "run=false" >> $GITHUB_OUTPUT
                  fi
                fi

      - name: Set up Python
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        run: pip install -r requirements.txt

      - name: Run unit tests
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        env:
          PYTHONPATH: src
        run: |
            echo "Running tests for ${{ matrix.module }}"
            python -m pytest tests/test_${{matrix.module}}.py 

      - name: Run module
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        env:
            PYTHONPATH: src
        run: |
          mkdir -p artifacts/${{ matrix.module }}
          
          if [ "${{ matrix.module }}" != "data_load" ]; then
            echo "Preparing data by running data_load..."
            python -m data_load
          fi
          
          echo "Running ${{ matrix.module }}"
          python -m ${{ matrix.module }} 2>&1 | tee artifacts/${{ matrix.module }}/run.log

      - name: Upload artifacts
        if: github.event_name != 'workflow_dispatch' || inputs.module == 'all' || inputs.module == matrix.module
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.module }}
          path: artifacts/${{ matrix.module }}